Repository Team4-Zighang/zighang_fe, pull requests merged in 2025-09, with the labels that each got.

#31 [FEATURE] QA
  public/icons/google_icon.svg
  public/icons/lock.svg
  src/app/_apis/onboarding.ts
  src/app/_apis/schemas/onboardingResponse.ts
  src/app/_components/common/Button.tsx
  src/app/_components/common/DropDown.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/common/JobRemoveModal.tsx
  src/app/_components/common/LoginModal.tsx
  src/app/_components/common/Pagination.tsx
  src/app/_components/common/SchoolDropDown.tsx
  src/app/alumni/components/HopeSameWork.tsx
  src/app/alumni/components/JobCard.tsx
  src/app/alumni/components/ManyBookmark.tsx
  src/app/alumni/components/ManyBookmarkHeader.tsx
  src/app/alumni/components/PopularCompany.tsx
  src/app/alumni/components/SearchAlumni.tsx
  src/app/alumni/page.tsx
  src/app/home/components/CardBack.tsx
  src/app/home/components/PostingLotto.tsx
  src/app/onboarding/components/OnBoardingContents.tsx
  src/app/onboarding/page.tsx
  src/hooks/mutation/useCardMutation.ts
  src/hooks/mutation/useOnboardingMutation.tsx
  src/hooks/queries/useAlumni.ts
  src/hooks/queries/useOnboarding.ts
  src/store/member.ts
  src/utils/schoolMap.ts
Labels: REFACTOR, FIX

#33 [FEATURE] QA
  src/app/_components/common/Header.tsx
  src/app/_components/common/NavigationPanel.tsx
  src/app/bookmark/components/AnalyzeCard.tsx
  src/app/bookmark/components/BookmarkFilterModal.tsx
  src/app/bookmark/components/BookmarkList.tsx
  src/app/bookmark/components/BookmarkListItem.tsx
  src/app/bookmark/components/EntireToggle.tsx
  src/app/globals.css
  src/app/home/components/JobElement.tsx
  src/app/home/components/JobGroup.tsx
  src/app/layout.tsx
  src/app/recruitment/[id]/components/BookmarkMemo.tsx
  src/app/recruitment/[id]/components/JobExitTab.tsx
  src/app/recruitment/[id]/components/RecruitFooter.tsx
  src/app/recruitment/[id]/components/TopAlert.tsx
  src/hooks/mutation/useBookmarkMutation.ts
  src/hooks/queries/useBookmark.ts
  src/utils/cleantext.ts
Labels: REFACTOR, FIX

#37 [FEATURE] QA2: 직군과 직무 연동
  src/app/onboarding/components/OnBoardingContents.tsx
  src/utils/jobRoleMap.ts
Labels: FEATURE, FIX

#42 [FEATURE] qa 재수정
  src/app/_components/common/Header.tsx
  src/app/bookmark/components/AnalyzeCard.tsx
  src/app/bookmark/components/BookmarkFilterModal.tsx
  src/app/bookmark/components/BookmarkList.tsx
  src/app/recruitment/[id]/components/JobDetail.tsx
  src/app/recruitment/[id]/components/JobExitTab.tsx
  src/app/recruitment/[id]/components/RecruitFooter.tsx
  src/hooks/mutation/useBookmarkMutation.ts
  src/hooks/queries/useBookmark.ts
  src/hooks/queries/useRecruitment.ts
Labels: FIX

#47 [FEATURE] qa 최종
  public/images/characters/zighang_character_1.png
  public/images/characters/zighang_character_1.webp
  public/images/characters/zighang_character_2.png
  public/images/characters/zighang_character_2.webp
  public/images/characters/zighang_character_3.png
  public/images/characters/zighang_character_3.webp
  public/images/characters/zighang_character_4.png
  public/images/characters/zighang_character_4.webp
  public/images/characters/zighang_character_5.png
  public/images/characters/zighang_character_5.webp
  public/images/characters/zighang_character_6.png
  public/images/characters/zighang_character_6.webp
  public/images/characters/zighang_character_7.png
  public/images/characters/zighang_character_7.webp
  public/images/characters/zighang_character_8.png
  public/images/characters/zighang_character_8.webp
  public/images/zighang_bookmark.png
  public/images/zighang_bookmark.webp
  public/images/zighang_bookmark_mo.png
  public/images/zighang_bookmark_mo.webp
  src/app/_components/common/Loader.tsx
  src/app/bookmark/components/AnalyzeCard.tsx
  src/app/bookmark/components/BookmarkBanner.tsx
  src/app/bookmark/components/BookmarkListItem.tsx
  src/app/recruitment/[id]/components/JobInfoBanner.tsx
  src/app/recruitment/[id]/components/RecruitFooter.tsx
  src/app/recruitment/[id]/components/SimilarJob.tsx
  src/app/recruitment/[id]/components/SimilarJobItem.tsx
  src/hooks/queries/useRecruitment.ts
  src/utils/character.ts
Labels: FIX
